// <auto-generated />
using ChocoStorageAPI.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChocoStorageAPI.Migrations
{
    [DbContext(typeof(ProductsInfoContext))]
    [Migration("20220614205120_addStockColumn")]
    partial class addStockColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("ChocoStorageAPI.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChocolateType")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductType")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChocolateType = 1,
                            Price = 300f,
                            ProductType = 0,
                            Stock = 50,
                            Weight = 0
                        },
                        new
                        {
                            Id = 2,
                            ChocolateType = 0,
                            Price = 300f,
                            ProductType = 0,
                            Stock = 20,
                            Weight = 70
                        },
                        new
                        {
                            Id = 3,
                            ChocolateType = 0,
                            Price = 500f,
                            ProductType = 0,
                            Stock = 20,
                            Weight = 120
                        },
                        new
                        {
                            Id = 4,
                            ChocolateType = 1,
                            Price = 300f,
                            ProductType = 2,
                            Stock = 4,
                            Weight = 70
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
