// <auto-generated />
using ChocoStorageAPI.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChocoStorageAPI.Migrations
{
    [DbContext(typeof(ProductsInfoContext))]
    [Migration("20220614232111_seedData2")]
    partial class seedData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("ChocoStorageAPI.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChocolateType")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductType")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChocolateType = 1,
                            Price = 300f,
                            ProductType = 0,
                            Stock = 50,
                            Weight = 70
                        },
                        new
                        {
                            Id = 2,
                            ChocolateType = 1,
                            Price = 500f,
                            ProductType = 0,
                            Stock = 20,
                            Weight = 110
                        },
                        new
                        {
                            Id = 3,
                            ChocolateType = 0,
                            Price = 300f,
                            ProductType = 0,
                            Stock = 20,
                            Weight = 70
                        },
                        new
                        {
                            Id = 4,
                            ChocolateType = 0,
                            Price = 500f,
                            ProductType = 0,
                            Stock = 20,
                            Weight = 110
                        },
                        new
                        {
                            Id = 5,
                            ChocolateType = 3,
                            Price = 400f,
                            ProductType = 1,
                            Stock = 4,
                            Weight = 120
                        },
                        new
                        {
                            Id = 6,
                            ChocolateType = 3,
                            Price = 600f,
                            ProductType = 1,
                            Stock = 20,
                            Weight = 180
                        },
                        new
                        {
                            Id = 7,
                            ChocolateType = 3,
                            Price = 750f,
                            ProductType = 1,
                            Stock = 20,
                            Weight = 300
                        },
                        new
                        {
                            Id = 8,
                            ChocolateType = 2,
                            Price = 400f,
                            ProductType = 1,
                            Stock = 4,
                            Weight = 120
                        },
                        new
                        {
                            Id = 9,
                            ChocolateType = 2,
                            Price = 600f,
                            ProductType = 1,
                            Stock = 20,
                            Weight = 180
                        },
                        new
                        {
                            Id = 10,
                            ChocolateType = 2,
                            Price = 750f,
                            ProductType = 1,
                            Stock = 20,
                            Weight = 300
                        },
                        new
                        {
                            Id = 11,
                            ChocolateType = 4,
                            Price = 400f,
                            ProductType = 1,
                            Stock = 4,
                            Weight = 120
                        },
                        new
                        {
                            Id = 12,
                            ChocolateType = 4,
                            Price = 600f,
                            ProductType = 1,
                            Stock = 20,
                            Weight = 180
                        },
                        new
                        {
                            Id = 13,
                            ChocolateType = 4,
                            Price = 750f,
                            ProductType = 1,
                            Stock = 20,
                            Weight = 300
                        },
                        new
                        {
                            Id = 14,
                            ChocolateType = 1,
                            Price = 350f,
                            ProductType = 2,
                            Stock = 10,
                            Weight = 70
                        },
                        new
                        {
                            Id = 15,
                            ChocolateType = 1,
                            Price = 500f,
                            ProductType = 2,
                            Stock = 20,
                            Weight = 160
                        },
                        new
                        {
                            Id = 16,
                            ChocolateType = 0,
                            Price = 350f,
                            ProductType = 2,
                            Stock = 20,
                            Weight = 70
                        },
                        new
                        {
                            Id = 17,
                            ChocolateType = 0,
                            Price = 500f,
                            ProductType = 2,
                            Stock = 2,
                            Weight = 160
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
